levis:
  name: "nginx"
  namespace: "kubeops"
  deployment:
    name: "nginx"
    labels:
      app: nginx
    annotations:
      app: nginx
    serviceAccount: microservice
    revisionHistoryLimit: 1
    replicas: 1
    strategy: 
      type: RollingUpdate
      rollingUpdate:
        maxSurge: "100%"
        maxUnavailable: "0%"
    matchLabels:
      app: nginx
    containers:
      name: "nginx"
      image: "nginx"
      imagePullPolicy: Always
      port: 80
      env:
        app: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      livenessProbe:
        path: /actuator/health/liveness
        port: "8080"
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 10
        failureThreshold: 10
        timeoutSeconds: 10
      readinessProbe:
        path: /actuator/health/readiness
        port: "8080"
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 10
        failureThreshold: 10
        timeoutSeconds: 10
  service:
    name: "nginx"
    labels:
      app: nginx
    annotations:
      app: nginx
    selector:
      app: nginx
    type: ClusterIP
    ports:
      name: "nginx"
      port: 80
      targetPort: 80
      nodePort: 30090  